### ISSUE TITLE
Pronto error

### ISSUE THREAD

**Issue by iammchat** [pocket-playlab/optimus-prime#38]
This error found on Circleci

command : `bundle exec pronto run --formatter=github`
error message : 
```
/home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/core/smell_repository.rb:22:in `initialize': uninitialized constant Reek::Core::SmellRepository::Configuration (NameError)
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/examiner.rb:62:in `new'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/examiner.rb:62:in `block in run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/source/source_repository.rb:41:in `each'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/source/source_repository.rb:41:in `each'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/examiner.rb:61:in `run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/reek-2.0.2/lib/reek/examiner.rb:32:in `initialize'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-reek-0.4.1/lib/pronto/reek.rb:14:in `new'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-reek-0.4.1/lib/pronto/reek.rb:14:in `run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:60:in `block in run_all_runners'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `map'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `run_all_runners'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:34:in `run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/lib/pronto/cli.rb:52:in `run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/gems/pronto-0.4.1/bin/pronto:6:in `<top (required)>'
	from /home/ubuntu/optimus-prime/vendor/bundle/ruby/2.2.0/bin/pronto:23:in `load'
```

**Comment by iammchat** [comment]
It because gem `reek` is update to new version (`2.0.2`).

**Comment by iammchat** [comment]
https://github.com/pocket-playlab/optimus-prime/pull/44

**Comment by troessner** [comment]
reek 2.1.0 has just been released, please upgrade.:)
